services:
  - type: web
    name: kreata-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l $PORT
    envVars:
      - key: REACT_APP_API_URL
        value: https://kreata-backend.onrender.com/api
        scope: build,runtime